f1 = open(str(input("fayl nomini kritng:  ")), "w")
f1.write("salom bolalar")
f1.close()
f2 = open("new.txt", "w")
f3 = open("new2.txt", "w")
f1 = open(str(input("qaysi fayldan: ")), "rt")
sonlar = f1.read()
son1 = sorted(sonlar, reverse=True)
f2.write(str(son1))
son2 = sorted(sonlar)
f3.write(str(son2))
f1.close()
f2.close()
f3.close()